name: Deploy API

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Setup key
      env:
        EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
      run: |
        echo "$EC2_PEM_KEY" >> $HOME/dev.pem
        cat $EC2_PEM_KEY
        cat $HOME/dev.pem
        chmod 400 $HOME/dev.pem
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/dev.pem ubuntu@ec2-3-18-138-83.us-east-2.compute.amazonaws.com 'bash -s' < deploy_script.sh
