name: Deploy

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Decode PEM key
        run: echo "${{ secrets.EC2_PEM_KEY }}" | base64 -d > /tmp/mar-dev.pem

      - name: Set SSH permissions
        run: chmod 400 /tmp/mar-dev.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/mar-dev.pem ec2-user@your-ec2-instance-public-dns 'bash -s' < .github/workflows/deploy_script.sh
